apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccountName: telegraf
      containers:
      - name: telegraf
        image: telegraf:alpine
        env:
        - name: INFLUXDB_DB
          value: "kube_metrics"
        - name: INFLUXDB_URL
          value: "http://influxdb:8086"
        - name: INFLUXDB_USER
          value: "telegraf"
        - name: INFLUXDB_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-passwords
              key: telegraf
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf/
      volumes:
      - name: config
        configMap:
          name: telegraf-config
          items:
          - key: config
            path: telegraf.conf
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  labels:
    tier: backend
data:
  config : |
    [global_tags]
      env = "$ENV"
    
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = true
      quiet = false
      logfile = ""
      omit_hostname = true

    [[outputs.influxdb]]
      timeout = "5s"
      urls = ["$INFLUXDB_URL"]
      database = "$INFLUXDB_DB"
      username = "$INFLUXDB_USER"
      password = "$INFLUXDB_USER_PASSWORD"
      user_agent = "telegraf_ki_k8s"
      
    [[outputs.file]]
      files = ["stdout"] 
      data_format = "influx"

    [[inputs.kubernetes]]
      url = "https://__ip__:10250"
      insecure_skip_verify = true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf
  labels:
    app: telegraf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: telegraf
  namespace: default
